"""Migración inicial

Revision ID: 43131cb7fc40
Revises: 
Create Date: 2023-10-13 23:36:32.833017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43131cb7fc40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_file_path'), 'files', ['file_path'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_path'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
